# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7ea85f9a3733bcf94d2a22217d8e44c8677af3ad0fba6f0e4d425cfcbf693a33a0afc05b2401f3534b17bd9c03e582cee5e2e67590894239c43edaaaaf45c14

test:
  secret_key_base: b07be5f7158c80c3623b8c15c876fd723728e59b34a55e3a57371a934fa550c431d0ff903733739848b3bad78e8b02222de0d884f34610e763c08ff0bb347f0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
